<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ashwin" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2019-09-27T15:25:36 EDT" time="0.233" errors="0">
  <testcase name="test3" time="0.056" classname="listeners.TestNgListeners">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.008" classname="listeners.TestNgListeners">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at listeners.TestNgListeners.test2(TestNgListeners.java:21)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="listeners.TestNgListeners">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
